### ISSUE TITLE
Globbing does not work across directories

### ISSUE THREAD

**Issue by starryeyez024** [chriseppstein/sass-globbing#12]
If you use add_import_path to load files from another directory like this:
http://note.io/1iE4dE9

and you try to use sass-globbing to import a batch of partials from the other directory, it fails. You have to import each partial one by one.

**Comment by unn** [comment]
Ran into this myself. Thanks for the work around @starryeyez024

**Comment by chriseppstein** [comment]
Should be fixed in `1.1.3`
