### ISSUE TITLE
Support being able to run parsing sass through --stdin rather than via path

### ISSUE THREAD

**Issue by matthew-andrews** [chriseppstein/sass-globbing#14]
Right now if you pass sass in via `--stdin` there is no `:filename` so I think it hits this line of code:-
https://github.com/chriseppstein/sass-globbing/blob/master/lib/sass/globbing/importer.rb#L43

I think in this case it would be reasonable to fall back to using `Dir.pwd` and in fact this can be 'hacked' to work by changing `def find` to:-

```ruby
def find(name, options)
  # In many places the code assumes that `options[:filename]` is the
  # file sass is running on - even though the only information that it
  # seems to actually need/use is the directory in which that file
  # lives.
  options[:filename] = Dir.pwd+'/hack' unless options[:filename]
  if name =~ GLOB
    find_glob(name, options[:filename], options) {
      "/* No files to import found in #{comment_safe(name)} */"
    }
  else
    super(name, options)
  end
end
```
But I don't like this implementation as it's really hacky.

(Also if this is fixed, it will fix https://github.com/docpad/docpad-plugin-sass/issues/22)

**Comment by chriseppstein** [comment]
this plugin requires a filename to work. import a file on disk that does the globbing.
