### ISSUE TITLE
Broken version 1.1.1?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [chriseppstein/sass-globbing#17]
I installed version 1.1.1, and I'm getting an error compiling: "File to import not found or unreadable: _nameOfPartial.scss", when I'm using syntax like this:

```
@import "components/*";
```

Uninstalled 1.1.1 and installed 1.1.0, and worked nice. Using compass

sass (3.3.7, 3.3.4, 3.2.19, 3.2.12)
compass (0.12.6)
compass-core (1.0.0.alpha.19)
compass-import-once (1.0.4)

**Comment by chriseppstein** [comment]
Fixed in `1.1.3`
