### ISSUE TITLE
Allow filename to contain an asterisk

### ISSUE THREAD

**Issue by julesbou** [chriseppstein/sass-globbing#18]
On a project we have a `main.scss` file:

```sass
@import 'modules/**/*.scss';
```

And the modules directory look like:

```
- modules
  - *.scss
  - foo.scss
```

I get following error `An @import loop has been found: main.scss imports itself`.

Is it possible to escape filename, or at least the asterisk part in it?

**Comment by chriseppstein** [comment]
Fixed in `1.1.3`
