### ISSUE TITLE
Globbing reporting 'no files to import found' when there are files in the directory in question

### ISSUE THREAD

**Issue by markweston** [chriseppstein/sass-globbing#22]
I'm using grunt-contrib-sass and requiring sass-globbing gem. I'm then running my grunt sass task through bundle exec (fails otherwise as it can't find sass-globbing) but my compiled css contains the following.

/* No files to import found in objects/**\/* */
/* No files to import found in components/**\/* */

Those two directories contain scss partials which can be compiled if I directly specify them in the import without using globbing. I removed version 1.1.1 of sass-globbing after seeing some issues relating to it and relative imports. 1.1.0 still gives me the same problem. If I try just using the /* pattern for files, which I was originally doing as I have no further subdirectories I have the same problem.

Also worth noting that grunt-contrib-sass reports no errors when compiling sass.

Any idea what is going on here.

**Comment by chriseppstein** [comment]
Fixed in `1.1.3`
