### ISSUE TITLE
sass globbing error on .scss

### ISSUE THREAD

**Issue by graydirt** [chriseppstein/sass-globbing#23]
hi there, 

im newbie on sass-globbing

i installed sass-globbing "gem install sass-globbing" on my directory path. and then i placed require 'sass-globbing' on my config.rb. But when i placed this @import 'vars/ * * / *'; on my style.scss i got an error. i got an error on putting an ASTERISK. because i think / * * / is a comment on notepad.

css/
----- style.scss
----- vars/colors.scss
	 

sass version 1.1.1
i also used koala as a tool for development for sass.

thanks!

**Comment by chriseppstein** [comment]
Fixed in `1.1.3`
