### ISSUE TITLE
Issues importing _underscored.scss, 'Not clear which file to import'

### ISSUE THREAD

**Issue by dougcassidy** [chriseppstein/sass-globbing#25]
error scss/signage.scss (Line 561: It's not clear which file to import for '@import "parts/*"'.
Candidates:
  parts/_new.scss
  parts/_new.scss
Please delete or rename all but one of these files.

My parts/ has only one _new.scss in it.  I was using the underscore to keep compass from making a parts/new.css in the output folder.  Works somewhat as expected without _underscore.

If i use just parts/new.scss, it works with globbing, the styles from new.scss go into my main css file, but also, a parts/new.css is created, which is superflous (because glob)

**Comment by cspilhere** [comment]
Hi @dougcassidy just try @import folder/*.*;
Was the only solution that works for me. ;)

**Comment by dougcassidy** [comment]
Thanks, I forget what was going on, back in Nov, but this is working for me:
@import 'partials[slash][star star][slash][star]';
Win7

**Comment by chriseppstein** [comment]
Should be fixed in `1.1.3`.
