### ISSUE TITLE
SASS Globbing ignoring sprite-feature

### ISSUE THREAD

**Issue by aloexDP** [chriseppstein/sass-globbing#30]
Hey there,

I have a main _component.scss and try to import multiple files in subdirectories with sass-globbing-pr-20:

@import '../Component/**/*';

In one of the inner files, I use the compass sprite feature to create a sprite:

@import 'icons/*.png';
@include all-icons-sprites;

Therefor compass throws "Undefined mixin 'all-icons-sprites'." 
This happens even if I change the import-path to a non-existing path, so it seems the image-import is skipped/ignored.

As soon as I move the icons-import to my _component.scss, the sprite becomes generated and my included files can access it.
Unfortunately this is no option for me, because I want to take different sprites for different included files. So I still want to import the sprite seperatly.

Did anyone experience the same issues or knows a solution?

Greetings
Alex

**Comment by chriseppstein** [comment]
fixed by c7dc8f3d341b9d5b76712be8b09439155e7bf858

**Comment by chriseppstein** [comment]
will be in 1.1.4

**Comment by chriseppstein** [comment]
Actually, I wasn't able to repro this so there's no fix. But try 1.1.5 and see if it helps.
