### ISSUE TITLE
Can't install sass-globbing with gem

### ISSUE THREAD

**Issue by zhangzan** [chriseppstein/sass-globbing#31]
error code

`
ERROR:  Could not find a valid gem 'sass-globbing' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/latest_specs.4.8.gz)
`

**Comment by chriseppstein** [comment]
seems like a problem with rubygems or your networking.

**Comment by parkr** [comment]
@zhangzan Try using `ruby.taobao.org` explained here: https://github.com/jekyll/jekyll/issues/1409#issue-17909206
