### ISSUE TITLE
sass-globbing not working

### ISSUE THREAD

**Issue by julienrondeau** [chriseppstein/sass-globbing#32]
Sass-globbing is installed properly on my system, but when I try to use it on a folder I got an error 

 "error scss/partials/ui/* (Line 1: File to import not found or unreadable: partials/ui/_buttons.scss.
Load path: Sass::Globbing::Importer)" on the first file of the folder.

_buttons.scss is a classic file with only 
button {
	border: none;
	outline: none;
	cursor: pointer;
}

And I got the same error even if I remove _buttons.scss with the next file.

any idea?

**Comment by chadpeppers** [comment]
I am also having this issue. Had to remove version 1.1.1 and install using 1.1.0 and it worked fine.

gem uninstall sass-globbing
sudo gem install sass-globbing -v 1.1.0

**Comment by chriseppstein** [comment]
fixed in 1.1.3

**Comment by praveenkgoswami** [comment]
I have faced the sass-globbing issue on windows 8.1
This has been resolved using the below code in xyz.scss file to compile:

@import "utilities**/**";

**Comment by bs-thomas** [comment]
@praveenkgoswami  I have no idea why that works, but it does!

Windows 10 1909, with the latest installs:
- ruby 2.7.0p0
- gem .1.2
- compass 1.0.3
- sass-globbing 1.1.5

The above was giving me error:

```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    error scss/main.scss (C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/sass-3.4.25/lib/sass/importers/filesystem.rb:152:in `[]': Invalid argument - C:/wamp64/www/website/www/backend/scss/config/*.)
```

No idea why it fails, it has always been working for several years (obviously with older installs).
In my code, I had this (and it used to work):

`@import "config/*.*";`

Now I fixed it by doing this:

`@import "config**/*";`

Yay! Thanks @praveenkgoswami

**Comment by proficientdesigners** [comment]
I had the same issue.
But, thanks now this is working for me too.

_Before:_
`@import "config/**";`

_After:_
`@import "config**/*";`

**My configs:**

- ruby - 2.7.0p0 (2019-12-25 revision 647ee6f091)
- gem - 3.1.2
- compass - 1.0.3 (Polaris)
- sass-globbing - 1.1.5

**Comment by karlwist0** [comment]
This is causing issues when working between mac and windows. Any ideas how to get round these errors with people working working on different OSs?

`folder/**/*` - works on mac
`folder**/*` - works on windows
