### ISSUE TITLE
Recursive Compilation while Watching

### ISSUE THREAD

**Issue by r4j4h** [chriseppstein/sass-globbing#8]
Hey there,

So I've found that when using sass-globbing with --watch I can easily get stuck in a loop. If I stop watching, make my changes, and then start, it compiles once just fine. If I make a change that it detects then it just keeps compiling the file over and over again.

The command my script uses is: `sass -r sass-globbing --watch ./:./`

I have tried with various combinations of folders and files and the behavior seems to be consistent. I will note I recently upgraded sass just before installing sass-globbing and it required me to manually install a dependency lib-rcevent or something similar if I recall, which the watcher uses, however sass's behavior without using sass-globbing appears identical to before the upgrade.

**Comment by chriseppstein** [comment]
Please test with 1.1.3 or greater.
